// Estado privado; interface partilhada em AppModules.core.
(() => {
// Ações da página; argumentos dinâmicos são dados, nunca código.

AppActions.register({
  "index-toggle-pw-e64aa5e": (el, event, args) => { AppModules.core.togglePw('login-password',el) },
  "index-toggle-pw-91c28cb": (el, event, args) => { AppModules.core.togglePw('register-confirm-password',el) },
  "index-toggle-pw-b15d284": (el, event, args) => { AppModules.core.togglePw('reset-password',el) },
  "index-toggle-pw-60cd192": (el, event, args) => { AppModules.core.togglePw('reset-confirm-password',el) },
  "index-set-auth-mode-76dbe1b": (el, event, args) => { AppModules.core.setAuthMode('forgot') },
  "index-toggle-sidebar-collapse-ad76e3e": (el, event, args) => { AppModules.core.toggleSidebarCollapse() },
  "index-show-view-f5d0286": (el, event, args) => { AppModules.core.showView('dashboard') },
  "index-show-view-3d0e569": (el, event, args) => { AppModules.core.showView('reservas') },
  "index-show-view-6fd615e": (el, event, args) => { AppModules.core.showView('calendario') },
  "index-show-view-68ce776": (el, event, args) => { AppModules.core.showView('eventos') },
  "index-show-view-afe629f": (el, event, args) => { AppModules.core.showView('notificacoes') },
  "index-show-view-772edb1": (el, event, args) => { AppModules.core.showView('invoice') },
  "index-show-view-a1dad0e": (el, event, args) => { AppModules.core.showView('hospedes') },
  "index-show-view-4899013": (el, event, args) => { AppModules.core.showView('alojamentos') },
  "index-show-view-aa6e09d": (el, event, args) => { AppModules.core.showView('precos') },
  "index-show-view-5da348e": (el, event, args) => { AppModules.core.showView('despesas') },
  "index-show-view-7f3ea84": (el, event, args) => { AppModules.core.showView('relatorios') },
  "index-show-view-447b5f9": (el, event, args) => { AppModules.core.showView('vouchers') },
  "index-show-view-56547aa": (el, event, args) => { AppModules.core.showView('definicoes') },
  "index-toggle-sidebar-aab962a": (el, event, args) => { AppModules.core.toggleSidebar() },
  "index-toggle-notif-76f1667": (el, event, args) => { AppModules.core.toggleNotif(event) },
  "index-toggle-user-menu-8773fdf": (el, event, args) => { AppModules.core.toggleUserMenu(event) },
  "index-stop-propagation-22499e1": (el, event, args) => { event.stopPropagation() },
  "index-open-profile-modal-f09c11a": (el, event, args) => { AppModules.core.openProfileModal() },
  "index-open-change-password-modal-8ca392f": (el, event, args) => { AppModules.core.openChangePasswordModal() },
  "index-open-sessions-modal-3435629": (el, event, args) => { AppModules.core.openSessionsModal() },
  "index-switch-account-80fec7e": (el, event, args) => { AppModules.core.switchAccount() },
  "index-logout-34b5979": (el, event, args) => { AppModules.core.logout() },
  "index-toggle-quick-action-menu-0334bc8": (el, event, args) => { AppModules.core.toggleQuickActionMenu(event) },
  "index-quick-action-nova-reserva-58ab5e7": (el, event, args) => { AppModules.core.quickActionNovaReserva() },
  "index-quick-action-novo-evento-0c85031": (el, event, args) => { AppModules.core.quickActionNovoEvento() },
  "index-quick-action-nova-notificacao-790a9b1": (el, event, args) => { AppModules.core.quickActionNovaNotificacao() },
  "index-go-to-today-checkins-13ac1c9": (el, event, args) => { AppModules.core.goToTodayCheckins() },
  "index-go-to-today-checkouts-ab5dad4": (el, event, args) => { AppModules.core.goToTodayCheckouts() },
  "index-go-to-pending-payments-c2f6a92": (el, event, args) => { AppModules.core.goToPendingPayments() },
  "index-quick-scan-receipt-from-dashboard-b9248c4": (el, event, args) => { AppModules.core.quickScanReceiptFromDashboard() },
  "index-toggle-page-filters-37b2c92": (el, event, args) => { AppModules.core.togglePageFilters('reservas-filter-panel', el) },
  "index-clear-reservas-filters-755ce3c": (el, event, args) => { AppModules.reservas.clearReservasFilters() },
  "index-set-reservas-period-operational-7d8f1aa": (el, event, args) => { AppModules.reservas.setReservasPeriodScope('operational') },
  "index-set-reservas-period-past-4a5c20e": (el, event, args) => { AppModules.reservas.setReservasPeriodScope('past') },
  "index-set-reservas-view-mode-8427567": (el, event, args) => { AppModules.reservas.setReservasViewMode('card') },
  "index-set-reservas-view-mode-a007aa5": (el, event, args) => { AppModules.reservas.setReservasViewMode('list') },
  "index-open-modal-d33d2af": (el, event, args) => { AppModules.reservas.openModal() },
  "index-toggle-reservas-filters-sheet-fc1a7a8": (el, event, args) => { AppModules.reservas.toggleReservasFiltersSheet(false) },
  "index-set-mobile-chip-83728e5": (el, event, args) => { AppModules.reservas.setMobileChip(el,'') },
  "index-set-mobile-chip-8c8b5fb": (el, event, args) => { AppModules.reservas.setMobileChip(el,'confirmada') },
  "index-set-mobile-chip-fe178f2": (el, event, args) => { AppModules.reservas.setMobileChip(el,'pendente') },
  "index-set-mobile-chip-931b8c9": (el, event, args) => { AppModules.reservas.setMobileChip(el,'pre_checkin') },
  "index-set-mobile-chip-d4ac248": (el, event, args) => { AppModules.reservas.setMobileChip(el,'cancelada') },
  "index-toggle-reservas-filters-sheet-0b7aaa9": (el, event, args) => { AppModules.reservas.toggleReservasFiltersSheet(true) },
  "index-sort-tabela-5568488": (el, event, args) => { AppModules.reservas.sortTabela('id') },
  "index-sort-tabela-c7b9063": (el, event, args) => { AppModules.reservas.sortTabela('created_at') },
  "index-sort-tabela-efd7eda": (el, event, args) => { AppModules.reservas.sortTabela('guest_name') },
  "index-sort-tabela-d346f74": (el, event, args) => { AppModules.reservas.sortTabela('accommodation_name') },
  "index-sort-tabela-1edfdab": (el, event, args) => { AppModules.reservas.sortTabela('check_in') },
  "index-sort-tabela-f3cf20f": (el, event, args) => { AppModules.reservas.sortTabela('check_out') },
  "index-sort-tabela-7d2728a": (el, event, args) => { AppModules.reservas.sortTabela('nights') },
  "index-sort-tabela-e075f5e": (el, event, args) => { AppModules.reservas.sortTabela('num_guests') },
  "index-sort-tabela-098b373": (el, event, args) => { AppModules.reservas.sortTabela('total_amount') },
  "index-sort-tabela-565790c": (el, event, args) => { AppModules.reservas.sortTabela('channel') },
  "index-sort-tabela-95d66a5": (el, event, args) => { AppModules.reservas.sortTabela('status') },
  "index-sort-tabela-c76331d": (el, event, args) => { AppModules.reservas.sortTabela('payment_status') },
  "index-cal-prev-928f754": (el, event, args) => { AppModules.calendario.calPrev() },
  "index-go-today-7e4aadc": (el, event, args) => { AppModules.calendario.goToday() },
  "index-cal-next-f650b4e": (el, event, args) => { AppModules.calendario.calNext() },
  "index-toggle-calendario-filters-sheet-15e0524": (el, event, args) => { AppModules.calendario.toggleCalendarioFiltersSheet(true) },
  "index-toggle-calendario-filters-sheet-02c6f4a": (el, event, args) => { AppModules.calendario.toggleCalendarioFiltersSheet(false) },
  "index-set-cal-mode-3871af2": (el, event, args) => { AppModules.calendario.setCalMode('calendar') },
  "index-set-cal-mode-3af7526": (el, event, args) => { AppModules.calendario.setCalMode('timeline') },
  "index-set-timeline-range-6b547a0": (el, event, args) => { AppModules.calendario.setTimelineRange(7) },
  "index-set-timeline-range-425a0ca": (el, event, args) => { AppModules.calendario.setTimelineRange(14) },
  "index-set-timeline-range-23c3f3a": (el, event, args) => { AppModules.calendario.setTimelineRange(30) },
  "index-open-block-modal-35e136a": (el, event, args) => { AppModules.bloqueios.openBlockModal() },
  "index-toggle-calendar-legend-filter-00e6bb2": (el, event, args) => { AppModules.calendario.toggleCalendarLegendFilter('confirmada') },
  "index-toggle-calendar-legend-filter-a60a470": (el, event, args) => { AppModules.calendario.toggleCalendarLegendFilter('pendente') },
  "index-cal-land-block-shortcut-4b8b5d3": (el, event, args) => { AppModules.calendario.calLandBlockShortcut() },
  "index-set-eventos-view-cb4fbd3": (el, event, args) => { AppModules.eventos.setEventosView('calendar') },
  "index-set-eventos-view-234943d": (el, event, args) => { AppModules.eventos.setEventosView('list') },
  "index-open-evento-modal-bd416ff": (el, event, args) => { AppModules.eventos.openEventoModal() },
  "index-eventos-prev-54a5761": (el, event, args) => { AppModules.eventos.eventosPrev() },
  "index-eventos-today-0bfed2b": (el, event, args) => { AppModules.eventos.eventosToday() },
  "index-eventos-next-30dc29c": (el, event, args) => { AppModules.eventos.eventosNext() },
  "index-set-eventos-mode-61381b6": (el, event, args) => { AppModules.eventos.setEventosMode('calendar') },
  "index-set-eventos-mode-58c5391": (el, event, args) => { AppModules.eventos.setEventosMode('timeline') },
  "index-set-eventos-timeline-range-a20c0cf": (el, event, args) => { AppModules.eventos.setEventosTimelineRange(7) },
  "index-set-eventos-timeline-range-b048876": (el, event, args) => { AppModules.eventos.setEventosTimelineRange(14) },
  "index-set-eventos-timeline-range-09b9304": (el, event, args) => { AppModules.eventos.setEventosTimelineRange(30) },
  "index-open-evento-modal-cf9c731": (el, event, args) => { AppModules.eventos.openEventoModal(null, new Date().toISOString().slice(0,10)) },
  "index-load-notifications-449f209": (el, event, args) => { AppModules.core.loadNotifications() },
  "index-open-manual-notification-modal-01af437": (el, event, args) => { AppModules.core.openManualNotificationModal() },
  "index-add-alojamento-ff5f8f7": (el, event, args) => { AppModules.alojamentos.addAlojamento() },
  "index-add-servico-e45a88c": (el, event, args) => { AppModules.alojamentos.addServico() },
  "index-delete-alojamento-3dd9b10": (el, event, args) => { AppModules.alojamentos.deleteAlojamento() },
  "index-save-alojamento-ffd34a4": (el, event, args) => { AppModules.alojamentos.saveAlojamento() },
  "index-show-aloj-tab-48e872d": (el, event, args) => { AppModules.alojamentos.showAlojTab('info') },
  "index-show-aloj-tab-14dc2b0": (el, event, args) => { AppModules.alojamentos.showAlojTab('comodidades') },
  "index-show-aloj-tab-af453af": (el, event, args) => { AppModules.alojamentos.showAlojTab('imagens') },
  "index-show-aloj-tab-4262e30": (el, event, args) => { AppModules.alojamentos.showAlojTab('rgpd') },
  "index-show-aloj-tab-e1cc4db": (el, event, args) => { AppModules.alojamentos.showAlojTab('bloqueios') },
  "index-show-aloj-tab-12b28da": (el, event, args) => { AppModules.alojamentos.showAlojTab('precos') },
  "index-copy-public-booking-link-34d2940": (el, event, args) => { AppModules.alojamentos.copyPublicBookingLink() },
  "index-open-public-booking-preview-4afe448": (el, event, args) => { AppModules.alojamentos.openPublicBookingPreview() },
  "index-add-extra-occupancy-option-4cbfdb2": (el, event, args) => { AppModules.alojamentos.addExtraOccupancyOption() },
  "index-switch-desc-lang-cea452c": (el, event, args) => { AppModules.alojamentos.switchDescLang('pt') },
  "index-switch-desc-lang-44c5447": (el, event, args) => { AppModules.alojamentos.switchDescLang('en') },
  "index-switch-desc-lang-990b505": (el, event, args) => { AppModules.alojamentos.switchDescLang('fr') },
  "index-switch-desc-lang-5cf5238": (el, event, args) => { AppModules.alojamentos.switchDescLang('es') },
  "index-switch-desc-lang-e272d0a": (el, event, args) => { AppModules.alojamentos.switchDescLang('de') },
  "index-switch-desc-lang-8de92cd": (el, event, args) => { AppModules.alojamentos.switchDescLang('it') },
  "index-switch-desc-lang-2d30faa": (el, event, args) => { AppModules.alojamentos.switchDescLang('nl') },
  "index-geocode-and-show-map-8af2978": (el, event, args) => { AppModules.alojamentos.geocodeAndShowMap() },
  "index-toggle-wifi-pass-8b16cb6": (el, event, args) => { AppModules.alojamentos.toggleWifiPass(el) },
  "index-remove-aloj-logo-1d70e78": (el, event, args) => { AppModules.alojamentos.removeAlojLogo() },
  "index-open-aloj-calendar-c518ff2": (el, event, args) => { AppModules.alojamentos.openAlojCalendar() },
  "index-handle-cover-zone-click-01563ad": (el, event, args) => { AppModules.alojamentos.handleCoverZoneClick(event) },
  "index-stop-propagation-79893be": (el, event, args) => { event.stopPropagation();document.getElementById('cover-input').click() },
  "index-stop-propagation-50f0688": (el, event, args) => { event.stopPropagation();AppModules.alojamentos.removeCoverImage() },
  "index-get-element-by-id-3f690f7": (el, event, args) => { document.getElementById('cover-input').click() },
  "index-get-element-by-id-4f20399": (el, event, args) => { document.getElementById('img-input').click() },
  "index-add-img-section-8bcd538": (el, event, args) => { AppModules.alojamentos.addImgSection() },
  "index-open-block-modal-1f10431": (el, event, args) => { AppModules.bloqueios.openBlockModal(document.getElementById('aloj-editing-id').value) },
  "index-set-hospedes-view-a7ea03d": (el, event, args) => { AppModules.hospedes.setHospedesView('cards') },
  "index-set-hospedes-view-f6da99d": (el, event, args) => { AppModules.hospedes.setHospedesView('lista') },
  "index-sort-hospedes-69c4e0a": (el, event, args) => { AppModules.hospedes.sortHospedes('name') },
  "index-sort-hospedes-efa5be0": (el, event, args) => { AppModules.hospedes.sortHospedes('email') },
  "index-sort-hospedes-958a44e": (el, event, args) => { AppModules.hospedes.sortHospedes('phone') },
  "index-sort-hospedes-f30b9d2": (el, event, args) => { AppModules.hospedes.sortHospedes('nationality') },
  "index-sort-hospedes-b478e5f": (el, event, args) => { AppModules.hospedes.sortHospedes('reservation_count') },
  "index-sort-hospedes-fbd6916": (el, event, args) => { AppModules.hospedes.sortHospedes('last_check_in') },
  "index-switch-invoice-tab-c5fa06a": (el, event, args) => { AppModules.invoice.switchInvoiceTab('conversas') },
  "index-switch-invoice-tab-f14ccbe": (el, event, args) => { AppModules.invoice.switchInvoiceTab('arquivo') },
  "index-switch-invoice-tab-aebdbcc": (el, event, args) => { AppModules.invoice.switchInvoiceTab('faturas') },
  "index-open-nova-conversa-b924301": (el, event, args) => { AppModules.invoice.openNovaConversa() },
  "index-open-voucher-modal-d7741bd": (el, event, args) => { AppModules.vouchers.openVoucherModal() },
  "index-if-a56dfb4": (el, event, args) => { if(event.target===el)AppModules.vouchers.closeVoucherModal() },
  "index-close-voucher-modal-6443b3b": (el, event, args) => { AppModules.vouchers.closeVoucherModal() },
  "index-save-voucher-fb5708f": (el, event, args) => { AppModules.vouchers.saveVoucher() },
  "index-show-precos-tab-c8142a3": (el, event, args) => { AppModules.precos.showPrecosTab('calendario') },
  "index-show-precos-tab-b9cf4ac": (el, event, args) => { AppModules.precos.showPrecosTab('config') },
  "index-cancel-precos-selection-93768a7": (el, event, args) => { AppModules.precos.cancelPrecosSelection() },
  "index-open-precos-bulk-start-picker-f612726": (el, event, args) => { AppModules.precos.openPrecosBulkStartPicker() },
  "index-open-precos-bulk-end-picker-25ee823": (el, event, args) => { AppModules.precos.openPrecosBulkEndPicker() },
  "index-toggle-precos-dow-e92fd4e": (el, event, args) => { AppModules.precos.togglePrecosDow('all') },
  "index-toggle-precos-dow-283b0a3": (el, event, args) => { AppModules.precos.togglePrecosDow(1) },
  "index-toggle-precos-dow-658e991": (el, event, args) => { AppModules.precos.togglePrecosDow(2) },
  "index-toggle-precos-dow-3541c35": (el, event, args) => { AppModules.precos.togglePrecosDow(3) },
  "index-toggle-precos-dow-5e856b8": (el, event, args) => { AppModules.precos.togglePrecosDow(4) },
  "index-toggle-precos-dow-a91ac75": (el, event, args) => { AppModules.precos.togglePrecosDow(5) },
  "index-toggle-precos-dow-58c20d0": (el, event, args) => { AppModules.precos.togglePrecosDow(6) },
  "index-toggle-precos-dow-f54905e": (el, event, args) => { AppModules.precos.togglePrecosDow(0) },
  "index-save-precos-bulk-a2b5954": (el, event, args) => { AppModules.precos.savePrecosBulk() },
  "index-clear-precos-bulk-form-6f21c23": (el, event, args) => { AppModules.precos.clearPrecosBulkForm() },
  "index-open-precos-period-modal-8207d94": (el, event, args) => { AppModules.precos.openPrecosPeriodModal(null) },
  "index-if-2b3ceaf": (el, event, args) => { if(event.target===el)AppModules.precos.closePrecosPeriodModal() },
  "index-close-precos-period-modal-a5a19e3": (el, event, args) => { AppModules.precos.closePrecosPeriodModal() },
  "index-save-precos-period-f5f5935": (el, event, args) => { AppModules.precos.savePrecosPeriod() },
  "index-switch-report-tab-ac3b876": (el, event, args) => { AppModules.relatorios.switchReportTab('faturamento') },
  "index-switch-report-tab-1e3e689": (el, event, args) => { AppModules.relatorios.switchReportTab('despesas') },
  "index-switch-report-tab-b53d754": (el, event, args) => { AppModules.relatorios.switchReportTab('lucro') },
  "index-switch-settings-tab-9fb9b21": (el, event, args) => { AppModules.core.switchSettingsTab('gcal') },
  "index-switch-settings-tab-7a90904": (el, event, args) => { AppModules.core.switchSettingsTab('database') },
  "index-switch-settings-tab-4789cef": (el, event, args) => { AppModules.core.switchSettingsTab('operations') },
  "index-switch-settings-tab-cb9fcd7": (el, event, args) => { AppModules.core.switchSettingsTab('emails') },
  "index-switch-settings-tab-a97cb74": (el, event, args) => { AppModules.core.switchSettingsTab('fornecedores') },
  "index-switch-settings-tab-9100a42": (el, event, args) => { AppModules.core.switchSettingsTab('push') },
  "index-switch-settings-tab-e9ee807": (el, event, args) => { AppModules.core.switchSettingsTab('equipa') },
  "index-connect-gmail-726ad90": (el, event, args) => { AppModules.core.connectGmail() },
  "index-disconnect-gmail-ed5ff65": (el, event, args) => { AppModules.core.disconnectGmail() },
  "index-test-gmail-ec29746": (el, event, args) => { AppModules.core.testGmail() },
  "index-connect-gcal-1a60f6c": (el, event, args) => { AppModules.core.connectGcal() },
  "index-disconnect-gcal-47b66d2": (el, event, args) => { AppModules.core.disconnectGcal() },
  "index-sync-all-gcal-dff39c4": (el, event, args) => { AppModules.core.syncAllGcal() },
  "index-clean-gcal-duplicates-a94c676": (el, event, args) => { AppModules.core.cleanGcalDuplicates() },
  "index-connect-google-tasks-8d04ef9": (el, event, args) => { AppModules.core.connectGoogleTasks() },
  "index-disconnect-google-tasks-c24b80b": (el, event, args) => { AppModules.core.disconnectGoogleTasks() },
  "index-sync-google-tasks-abdbefc": (el, event, args) => { AppModules.core.syncGoogleTasks() },
  "index-clean-gtasks-duplicates-3987485": (el, event, args) => { AppModules.core.cleanGtasksDuplicates() },
  "index-feature-action-9be548a": (el, event, args) => { AppModules.core.featureAction('exportAlojamentosXLS') },
  "index-feature-action-692e885": (el, event, args) => { AppModules.core.featureAction('exportAlojamentosPDF') },
  "index-feature-action-283c8c8": (el, event, args) => { AppModules.core.featureAction('exportReservasXLS') },
  "index-feature-action-3afa930": (el, event, args) => { AppModules.core.featureAction('exportReservasPDF') },
  "index-feature-action-2251788": (el, event, args) => { AppModules.core.featureAction('exportHospedesXLS') },
  "index-feature-action-b14c826": (el, event, args) => { AppModules.core.featureAction('exportHospedesPDF') },
  "index-export-d-b-3cb0ae1": (el, event, args) => { AppModules.core.exportDB() },
  "index-seed-fornecedores-ac7b365": (el, event, args) => { AppModules.definicoes.seedFornecedores() },
  "index-add-fornecedor-de1bbb0": (el, event, args) => { AppModules.definicoes.addFornecedor() },
  "index-enable-push-notifications-bd65c9a": (el, event, args) => { AppModules.definicoes.enablePushNotifications() },
  "index-disable-push-notifications-c8908b8": (el, event, args) => { AppModules.definicoes.disablePushNotifications() },
  "index-send-test-push-b565ec2": (el, event, args) => { AppModules.definicoes.sendTestPush() },
  "index-invite-team-member-1530cb9": (el, event, args) => { AppModules.definicoes.inviteTeamMember() },
  "index-close-guest-modal-6f28c13": (el, event, args) => { AppModules.hospedes.closeGuestModal() },
  "index-save-guest-edit-7605d58": (el, event, args) => { AppModules.hospedes.saveGuestEdit() },
  "index-close-image-lightbox-f9d85d4": (el, event, args) => { AppModules.alojamentos.closeImageLightbox() },
  "index-if-136ef98": (el, event, args) => { if(event.target===el)AppModules.eventos.closeEventoModal() },
  "index-close-evento-modal-1ee2065": (el, event, args) => { AppModules.eventos.closeEventoModal() },
  "index-delete-evento-from-modal-a397cde": (el, event, args) => { AppModules.eventos.deleteEventoFromModal() },
  "index-save-evento-4f346cc": (el, event, args) => { AppModules.eventos.saveEvento() },
  "index-if-1bd17c8": (el, event, args) => { if(event.target===el)AppModules.core.closeManualNotificationModal() },
  "index-close-manual-notification-modal-b2a8800": (el, event, args) => { AppModules.core.closeManualNotificationModal() },
  "index-save-manual-notification-603e7ab": (el, event, args) => { AppModules.core.saveManualNotification() },
  "index-if-fab44c2": (el, event, args) => { if(event.target===el)AppModules.core.closeExportColumnPicker() },
  "index-close-export-column-picker-75159c8": (el, event, args) => { AppModules.core.closeExportColumnPicker() },
  "index-export-cols-select-all-b1f5c7c": (el, event, args) => { AppModules.core._exportColsSelectAll(true) },
  "index-export-cols-select-all-eeeb75e": (el, event, args) => { AppModules.core._exportColsSelectAll(false) },
  "index-confirm-export-column-picker-6e5e7fe": (el, event, args) => { AppModules.core.confirmExportColumnPicker() },
  "index-request-close-reserva-modal-92eb2a6": (el, event, args) => { AppModules.reservas.requestCloseReservaModal() },
  "index-discard-reserva-draft-53f0676": (el, event, args) => { AppModules.reservas.discardReservaDraft() },
  "index-wiz-toggle-extra-rooms-ce30293": (el, event, args) => { AppModules.reservas.wizToggleExtraRooms() },
  "index-apply-nightly-to-all-f99c949": (el, event, args) => { AppModules.reservas.applyNightlyToAll() },
  "index-reset-nightly-overrides-1d673fa": (el, event, args) => { AppModules.reservas.resetNightlyOverrides() },
  "index-set-form-discount-type-be84a88": (el, event, args) => { AppModules.reservas.setFormDiscountType('pct') },
  "index-set-form-discount-type-a4a7670": (el, event, args) => { AppModules.reservas.setFormDiscountType('eur') },
  "index-open-05fd9c5": (el, event, args) => { AppDatePicker.open(document.getElementById('f-nascimento'),{isBirthDate:true}) },
  "index-verify-backoffice-voucher-163d348": (el, event, args) => { AppModules.reservas.verifyBackofficeVoucher() },
  "index-save-reserva-0326a52": (el, event, args) => { AppModules.reservas.saveReserva() },
  "index-if-0109c33": (el, event, args) => { if(event.target===el)AppUI.closeModal(el) },
  "index-close-modal-89efa48": (el, event, args) => { AppUI.closeModal('detail-bg') },
  "index-nova-reserva-87b11c0": (el, event, args) => { AppModules.core.novaReserva() },
  "index-close-side-drawer-28b0ec9": (el, event, args) => { AppModules.core.closeSideDrawer() },
  "index-show-view-2517b76": (el, event, args) => { AppModules.core.showView('dashboard');AppModules.core.closeSideDrawer() },
  "index-show-view-3896a1c": (el, event, args) => { AppModules.core.showView('reservas');AppModules.core.closeSideDrawer() },
  "index-show-view-ee36455": (el, event, args) => { AppModules.core.showView('calendario');AppModules.core.closeSideDrawer() },
  "index-show-view-5e22dbf": (el, event, args) => { AppModules.core.showView('eventos');AppModules.core.closeSideDrawer() },
  "index-show-view-5680375": (el, event, args) => { AppModules.core.showView('hospedes');AppModules.core.closeSideDrawer() },
  "index-show-view-78c396d": (el, event, args) => { AppModules.core.showView('notificacoes');AppModules.core.closeSideDrawer() },
  "index-show-view-e180a25": (el, event, args) => { AppModules.core.showView('alojamentos');AppModules.core.closeSideDrawer() },
  "index-show-view-9dc1e16": (el, event, args) => { AppModules.core.showView('precos');AppModules.core.closeSideDrawer() },
  "index-show-view-05eda4c": (el, event, args) => { AppModules.core.showView('despesas');AppModules.core.closeSideDrawer() },
  "index-show-view-a532708": (el, event, args) => { AppModules.core.showView('relatorios');AppModules.core.closeSideDrawer() },
  "index-show-view-9eff395": (el, event, args) => { AppModules.core.showView('definicoes');AppModules.core.switchSettingsTab('emails');AppModules.core.closeSideDrawer() },
  "index-show-view-ef3e4be": (el, event, args) => { AppModules.core.showView('definicoes');AppModules.core.closeSideDrawer() },
  "index-close-side-drawer-0395508": (el, event, args) => { AppModules.core.closeSideDrawer();AppModules.core.openProfileModal() },
  "index-close-side-drawer-5e6ac44": (el, event, args) => { AppModules.core.closeSideDrawer();AppModules.core.openChangePasswordModal() },
  "index-close-side-drawer-f44ae7e": (el, event, args) => { AppModules.core.closeSideDrawer();AppModules.core.openSessionsModal() },
  "index-close-side-drawer-b4bebaf": (el, event, args) => { AppModules.core.closeSideDrawer();AppModules.core.switchAccount() },
  "index-close-side-drawer-4a3b8ba": (el, event, args) => { AppModules.core.closeSideDrawer();AppModules.core.logout() },
  "index-if-3215315": (el, event, args) => { if(event.target===el)AppModules.core.closeProfileModal() },
  "index-close-profile-modal-7a8122e": (el, event, args) => { AppModules.core.closeProfileModal() },
  "index-toggle-pw-56ac005": (el, event, args) => { AppModules.core.togglePw('pf-password',el) },
  "index-if-370b5e1": (el, event, args) => { if(event.target===el)AppModules.core.closeSessionsModal() },
  "index-close-sessions-modal-7608ce6": (el, event, args) => { AppModules.core.closeSessionsModal() },
  "index-revoke-other-sessions-d00709f": (el, event, args) => { AppModules.core.revokeOtherSessions() },
  "index-if-d444ee6": (el, event, args) => { if(event.target===el)AppModules.core.closeChangePasswordModal() },
  "index-close-change-password-modal-efbfd41": (el, event, args) => { AppModules.core.closeChangePasswordModal() },
  "index-toggle-pw-074b3fd": (el, event, args) => { AppModules.core.togglePw('cp-current',el) },
  "index-toggle-pw-1c49c0f": (el, event, args) => { AppModules.core.togglePw('cp-new',el) },
  "index-toggle-pw-1219ceb": (el, event, args) => { AppModules.core.togglePw('cp-confirm',el) },
}, "click");

AppActions.register({
  "index-search-reservas-6596e25": (el, event, args) => { AppModules.reservas.searchReservas(el) },
  "index-eventos-list-query-changed-d8f42d6": (el, event, args) => { AppModules.eventos.eventosListQueryChanged() },
  "index-render-alojamentos-55a548a": (el, event, args) => { AppModules.alojamentos.renderAlojamentos() },
  "index-refresh-amenities-filter-8bb980a": (el, event, args) => { AppModules.alojamentos.refreshAmenitiesFilter() },
  "index-render-hospedes-2b72f03": (el, event, args) => { AppModules.hospedes.renderHospedes() },
  "index-filter-invoice-conversas-eb1249d": (el, event, args) => { AppModules.invoice.filterInvoiceConversas() },
  "index-on-manual-total-input-9a5bf38": (el, event, args) => { AppModules.reservas.onManualTotalInput(el.value) },
  "index-calc-total-ede923f": (el, event, args) => { AppModules.reservas.calcTotal() },
  "index-wiz-guest-search-ba4bf00": (el, event, args) => { AppModules.reservas.wizGuestSearch(el.value) },
  "index-update-wiz-summary-35ca320": (el, event, args) => { AppModules.reservas.updateWizSummary() },
  "index-handle-birth-date-input-6742f58": (el, event, args) => { AppModules.reservas.handleBirthDateInput(el) },
  "index-on-amount-paid-change-104efde": (el, event, args) => { AppModules.reservas.onAmountPaidChange() },
  "index-to-upper-case-da41d26": (el, event, args) => { el.value=el.value.toUpperCase() },
  "index-update-profile-password-visibility-293b4c8": (el, event, args) => { AppModules.core.updateProfilePasswordVisibility() },
}, "input");

AppActions.register({
  "index-clear-res-exact-date-filter-097f687": (el, event, args) => { AppModules.reservas.clearResExactDateFilter();AppModules.reservas.renderTabela() },
  "index-render-tabela-3c1624a": (el, event, args) => { AppModules.reservas.renderTabela() },
  "index-render-cal-view-68e81d3": (el, event, args) => { AppModules.calendario.renderCalView() },
  "index-eventos-list-query-changed-962fe8b": (el, event, args) => { AppModules.eventos.eventosListQueryChanged({ immediate: true }) },
  "index-render-alojamentos-eccef8d": (el, event, args) => { AppModules.alojamentos.renderAlojamentos() },
  "index-on-aloj-tipo-change-7469612": (el, event, args) => { AppModules.alojamentos.onAlojTipoChange() },
  "index-on-aloj-parent-change-4ab93cd": (el, event, args) => { AppModules.alojamentos.onAlojParentChange() },
  "index-upload-aloj-logo-56d5027": (el, event, args) => { AppModules.alojamentos.uploadAlojLogo(el) },
  "index-update-voucher-value-label-5b6b115": (el, event, args) => { AppModules.vouchers.updateVoucherValueLabel() },
  "index-on-precos-aloj-change-d356643": (el, event, args) => { AppModules.precos.onPrecosAlojChange() },
  "index-set-report-year-d751a81": (el, event, args) => { AppModules.relatorios.setReportYear(el.value) },
  "index-set-report-month-8b615d3": (el, event, args) => { AppModules.relatorios.setReportMonth(el.value) },
  "index-set-report-acc-id-5d25e0a": (el, event, args) => { AppModules.relatorios.setReportAccId(el.value) },
  "index-set-desp-year-4602415": (el, event, args) => { AppModules.relatorios.setDespYear(el.value) },
  "index-set-desp-month-63b5da2": (el, event, args) => { AppModules.relatorios.setDespMonth(el.value) },
  "index-set-lucro-year-bb5bf08": (el, event, args) => { AppModules.relatorios.setLucroYear(el.value) },
  "index-set-lucro-acc-id-ecf6900": (el, event, args) => { AppModules.relatorios.setLucroAccId(el.value) },
  "index-save-gcal-sync-settings-661beb8": (el, event, args) => { AppModules.core.saveGcalSyncSettings() },
  "index-feature-action-3893769": (el, event, args) => { AppModules.core.featureAction('importAlojamentosXLS', el) },
  "index-set-export-reminder-c0631ba": (el, event, args) => { AppModules.core.setExportReminder('alojamentos_xls', el.value) },
  "index-set-export-reminder-79573f2": (el, event, args) => { AppModules.core.setExportReminder('alojamentos_pdf', el.value) },
  "index-feature-action-71a5955": (el, event, args) => { AppModules.core.featureAction('importReservasXLS', el) },
  "index-set-export-reminder-8c8d9db": (el, event, args) => { AppModules.core.setExportReminder('reservas_xls', el.value) },
  "index-set-export-reminder-de7f07d": (el, event, args) => { AppModules.core.setExportReminder('reservas_pdf', el.value) },
  "index-feature-action-de7d6f8": (el, event, args) => { AppModules.core.featureAction('importHospedesXLS', el) },
  "index-set-export-reminder-7f41ba7": (el, event, args) => { AppModules.core.setExportReminder('hospedes_xls', el.value) },
  "index-set-export-reminder-cbd028e": (el, event, args) => { AppModules.core.setExportReminder('hospedes_pdf', el.value) },
  "index-import-d-b-d60a8a8": (el, event, args) => { AppModules.core.importDB(el) },
  "index-set-export-reminder-69d5a9c": (el, event, args) => { AppModules.core.setExportReminder('cliente_zip', el.value) },
  "index-save-auto-task-settings-496a39c": (el, event, args) => { AppModules.core.saveAutoTaskSettings() },
  "index-save-push-prefs-0f45e7b": (el, event, args) => { AppModules.definicoes.savePushPrefs() },
  "index-calc-total-a1c3bab": (el, event, args) => { AppModules.reservas.calcTotal();AppModules.reservas.updateWizSummary();AppModules.reservas._availTimer&&clearTimeout(AppModules.reservas._availTimer);AppModules.reservas._availTimer=setTimeout(AppModules.reservas.fetchSuiteAvailability,400) },
  "index-update-num-hospedes-ef410f4": (el, event, args) => { AppModules.reservas.updateNumHospedes();AppModules.reservas.renderSuiteCards();AppModules.reservas.calcTotal();AppModules.reservas.renderExtraGuests() },
  "index-calc-total-a239bdf": (el, event, args) => { AppModules.reservas.calcTotal() },
  "index-calc-total-8bcd488": (el, event, args) => { AppModules.reservas.calcTotal();AppModules.reservas.updateWizSummary() },
  "index-update-foreign-requirements-2ec6793": (el, event, args) => { AppModules.reservas.updateForeignRequirements() },
  "index-on-payment-status-change-93354d3": (el, event, args) => { AppModules.reservas.onPaymentStatusChange() },
}, "change");

AppActions.register({
  "index-prevent-default-e179d9b": (el, event, args) => { event.preventDefault();el.classList.add('drag-over') },
  "index-prevent-default-b00197c": (el, event, args) => { event.preventDefault();el.style.background='rgba(74,127,165,.08)' },
}, "dragover");

AppActions.register({
  "index-remove-1227cde": (el, event, args) => { el.classList.remove('drag-over') },
  "index-element-c6c7e81": (el, event, args) => { el.style.background='' },
}, "dragleave");

AppActions.register({
  "index-handle-cover-drop-1d111ca": (el, event, args) => { AppModules.alojamentos.handleCoverDrop(event) },
  "index-handle-img-drop-dd5a216": (el, event, args) => { AppModules.alojamentos.handleImgDrop(event) },
}, "drop");

AppActions.register({
  "index-cover-drag-start-d371bdf": (el, event, args) => { AppModules.alojamentos.coverDragStart(event) },
}, "dragstart");

AppActions.register({
  "index-cover-drag-end-471451e": (el, event, args) => { AppModules.alojamentos.coverDragEnd(event) },
}, "dragend");

AppActions.register({
  "index-if-8ac507c": (el, event, args) => { if(event.key==='Enter')AppModules.definicoes.addFornecedor() },
  "index-if-1bd98b0": (el, event, args) => { if(event.key==='Enter')AppModules.definicoes.sendTestPush() },
}, "keydown");

AppActions.register({
  "index-snapshot-manual-distrib-weights-5b88f57": (el, event, args) => { AppModules.reservas.snapshotManualDistribWeights() },
  "index-remove-attribute-3e4a1fd": (el, event, args) => { el.removeAttribute('readonly') },
}, "focus");

AppActions.register({
  "index-normalize-birth-date-input-19ea83e": (el, event, args) => { AppModules.reservas.normalizeBirthDateInput(el);AppModules.reservas.calcTotal();AppModules.reservas.updateSpecialRateHints() },
}, "blur");

AppActions.register({
  "index-prevent-default-9940257": (el, event, args) => { event.preventDefault();AppModules.core.submitProfile() },
  "index-prevent-default-8a19dfa": (el, event, args) => { event.preventDefault();AppModules.core.submitChangePassword() },
}, "submit");

})();
